loggly/install-script

Linux Script/configure-linux.sh
Mac Script/README.md
Mac Script/configure-mac.sh
Modular Scripts/Apache2/configure-apache.sh
Modular Scripts/File Monitoring/configure-file-monitoring.sh
Modular Scripts/Nginx/configure-nginx.sh
Modular Scripts/S3Logs Monitoring/configure-s3-file-monitoring.sh
Modular Scripts/Tomcat/configure-tomcat.sh
publish.sh

1. Added support to Debian OS
2. Added check for syslog-ng
3. Added checks if the logs are parsed in Loggly
4. Added support to suppress prompts in scripts
5. Updated Links
6. Bug Fixes

Enhancements

---

Linux Script/configure-linux.sh

in my AWS environment ICMP isn't open, but 514 is.  So I added a telnet check in the if block.

also try telnet to check if host is up

---

Modular Scripts/Nginx/configure-nginx.sh

- By default, the script will send the apache logs securely on port 6514
- If the users give --insecure in the command then he/she can switch to insecure sending.
- For system logs, the script will give a prompt to send them securely. If user gives input in "Yes" then the script will download the certificate and "rsyslog-gnutls" package and will change the 22-loggly.conf content to the secured one.

Add TLS support to Nginx script

---

Linux Script/configure-linux.sh

1- Add "-y" option in the package download command
2- Corrected distribution name for Redhat system from "redhat" to "red".

Update command for downloading Rsyslog-gnutls package

---

Linux Script/configure-linux.sh

@mchaudhary @mostlyjason,  I have modified code to implement below requirements in the script:
1. If TLS package couldn't be installed then the script will show a warning message "**The rsyslog-gnutls package could not be download automatically because your package manager could not be found.**" and will prompt to switch to insecure mode.(In **prompt mode**)
2. If TLS package couldn't be installed then the script will automatically install the insecure mode.(In **suppress mode**)
3. I have added a new flag **--force-secure** that will first show a warning message "**The rsyslog-gnutls package could not be download automatically because your package manager could not be found. Please install it and restart the rsyslog service to send logs to Loggly.**" and then will install the secure mode …

switch-to-insecure-mode-if-tlsdownload-fails

---

Linux Script/configure-linux.sh

-Fixed switching to the insecure mode when yum or apt-get is available but rsyslog-gnutls package could not be downloaded for any reason. 
-Fixed issue with **--force-secure + --suppress** option. Earlier, the script was switching to insecure mode even if both of these flags were used. So, the force secure mode became unusable in that case.

Fix issues

---

Modular Scripts/Apache2/configure-apache.sh

@mchaudhary @mostlyjason In this PR, I have added a new systemctl command that will check whether any service is installed or not. The output of the command **systemctl list-unit-files httpd.service** is below(if installed):
```
UNIT FILE     STATE
httpd.service disabled
1 unit files listed.
```
If not installed then the output is as below:
```
UNIT FILE STATE
0 unit files listed.
```
So I used `grep` to extract the installed service name from the command output. I also used `$(which systemctl)` because on CentOS 6, systemctl command doesn't work and if user has not installed the httpd and run our script then it will first evaluate the condition `if [ -f /etc/init.d/$SERVICE ]; then` and it will not find the httpd service at that path then script will try to execute the next conditon in …

Add systemctl command to check for apache service

---

Linux Script/configure-linux.sh

@mchaudhary, @mostlyjason, In this PR, I have added 4 new fields listed below to get logged on Loggly-
**Please note that all below fields contain the value either in true or false so we can easily identify which flag was used when the user ran the command by looking at its value on Loggly Search UI.**
**secure-sending** - This field will tell whether the script ran in the **secure mode** or in a **insecure mode**.
**suppress-enabled** - This field will tell whether the script ran in **suppress mode** or not.
**force-secure-enabled** - This field will tell whether the script ran in **--force-secure mode** or not.
**loggly-removed** - This field will tell if the user has removed the Loggly configuration from his machine. 
Please review.

New flags logging support

---

Linux Script/configure-linux.sh

@mchaudhary @mostlyjason, In this PR, I am checking whether the user is running the dependent scripts in **secure** or **insecure** mode, based on the script running mode, I am checking if the existing port in **22-loggly.conf** file is same as the running mode of the script For example if the user is running the **file-monitoring** script in **secure mode** but **22-loggly.conf** is set with **insecure** config then the script will prompt to switch **system config to secure mode as well and vice versa**. 
Please review.

Check and switch existing logging mode

---

Modular Scripts/Apache2/configure-apache.sh

- By default, the script will send the apache logs securely on port 6514
- If the users give --insecure in the command then he/she can switch to insecure sending.

Tls support apache

---

Linux Script/configure-linux.sh
Modular Scripts/File Monitoring/configure-file-monitoring.sh

I changed configure-linux.sh and configure-file-monitoring.sh scripts to add TLS support to both the scripts.
These are covering below points.
* Added TLS support to configure-linux.sh file 
* Added TLS support to configure-file-monitoring.sh file
- Check if 6514 is open
- Add insecure parameter
- Prompt if we should switch to insecure mode if system logs are insecure, or overwrite them with secure mode
- If silent or no prompt mode is on and system logs are insecure, log a warning and overwrite system config with secure settings

Add TLS support for file monitoring

---

Linux Script/configure-linux.sh

@mchaudhary @mostlyjason In this PR, I have added a new function that will check if the required dependencies to run the script are not installed. I also did some refactoring work like function name changes etc. Please review.

added function to check all dependencies

---

.editorconfig
Linux Script/configure-linux.sh
Mac Script/configure-mac.sh
Modular Scripts/Apache2/configure-apache.sh
Modular Scripts/File Monitoring/configure-file-monitoring.sh
Modular Scripts/Nginx/configure-nginx.sh
Modular Scripts/S3Logs Monitoring/configure-s3-file-monitoring.sh
Modular Scripts/Tomcat/configure-tomcat.sh
ltomcatsetup.sh

I have fixed the indentation of the scripts to 2 spaces.
Kindly review and merge.

Fix the indentation to 2 spaces

---

Modular Scripts/Tomcat/configure-tomcat.sh

@mchaudhary @mostlyjason In this PR I added the TLS configuration in tomcat script and **--insecure** parameter for the insecure logging. Currently, I am testing this new script on different distributions so testing work is in progress. 
Please review.

Add TLS support in Tomcat Script

---

Modular Scripts/Tomcat/configure-tomcat.sh

@mchaudhary @mostlyjason I have corrected the script indentation to 2 spaces and also tested it to cross verify the script behavior and everything looked fine to me. Please review and merge.

fix indentation to 2 spaces of tomcat script

---

Linux Script/configure-linux.sh

@mchaudhary @mostlyjason I have tested the below command on most of the widely used distributions and the script execution looked fine to me.

Modify UUID generate command and resolve hanging issue

---

Linux Script/configure-linux.sh

@mchaudhary In this PR, I have put a check to validate if the subdomain contains **.loggly.com** with it. The user must enter only the first string of his account name for the subdomain. If user enters the complete account name, the script will mark this subdomain invalid, display an error message and will exit. 
I have also added a clear exit message so the users do not confuse. 
Please review.

Resolve invalid subdomain issue

---

AWSscripts/SQS3script.py

AWS CLI `.aws/credentials` can have more than one user.  Previously, the script would default to the last set of access/secret keys, which may not have administrative privileges.  If the user does have multiple users, this will allow them to pass in the admin name with administrative permissions.
Note: This is different than "user" which will have access to the s3 bucket and not necessarily have admin privileges.
@Shwetajain148 can you please review.  Can you email Pankaj to test as well after approval/merge.
Thank you

Add admin args option

---

AWSscripts/SQS3script.py

`os.environ['HOME']` does not work on windows, `os.path.expanduser("~")` will work cross platform

use expanduser to get home path - fix for windows

---

Linux Script/update-loggly-certificate.sh

Hi, I was working on a issue #113 and found that the GitHub code is different than the code running in production i.e. in deployed script. Please see the line [#306](https://github.com/loggly/install-script/blob/master/Linux%20Script/update-loggly-certificate.sh#L306) it contains **grep "200 OK"** but if you download the script and see the code it's **grep "200"** there. 
To match the GitHub's code with deployed script, I have raised this PR. Please review and merge. 
Thanks.

Update GitHub Code to match with deployed script

---

Linux Script/configure-linux.sh

also write out http_code to avoid using grep to check for 200

use "curl -L" to follow redirects during subdomain check

---

Modular Scripts/Apache2/configure-apache.sh

-added rsyslog restart after keeping old configuration
-added possibility to curl server to produce an access log record

added curl on apache server and rsyslog restart

---

AWSscripts/SQS3script.py

We don't need all SQS permissions so we should set only those that are really needed. This PR limits that.

LOG-6197 - Limit SQS permissions only to those really needed

---

Linux Script/configure-linux.sh

Resolves CI https://swicloud.atlassian.net/browse/LOG-7606
Just adds validation that `count`, which was fetched from our API, returns a valid number, if not, it means that no event were found, so set the value to `0`. Otherwise the script prints `configure-linux.sh: line 902: [: : integer expression expected` which is propagated further and the output doesn't look clean.

LOG-6073 Add default value for count search

---

Mac Script/configure-mac.sh

Fixes:
- fluentd gem install
- password with spaces
- uuid generation
- integer comparisons

LOG-7592 - fix Mac script

---

Linux Script/configure-linux.sh

This reverts commit e05e97753a8745949f7683813b7859fe41293f5e.
According to Jarvis:
Hi Jiri, I just wanted to inform you that it seems like the automatic script is not working properly. It is stuck at this area of the code
```
logMsgToConfigSysLog "INFO" "INFO: Verifying if the logs made it to Loggly."
logMsgToConfigSysLog "INFO" "INFO: Verification # $counter of total $maxCounter."
#get the final count of file logs for past 15 minutes
searchAndFetch fileLatestLogCount "$queryUrl"
let counter=$counter+1
```
I've tested this on two environment, one EC2 Linux 2 and Ubuntu image in AWS, both are stuck at the verification part
This happens [here](https://github.com/loggly/install-script/blob/e05e97753a8745949f7683813b7859fe41293f5e/Linux%20Script/configure-linux.sh#L760)

Revert "LOG-6073 Add default value for count search"

---

Linux Script/configure-linux.sh

**Description**
- [JIRA](https://swicloud.atlassian.net/browse/LOG-8159)
- https://www.loggly.com/docs/sending-logs-unixlinux-system-setup/
- replace usage of the Loggly certificate for using CA bundle stored in OS trust store -> this bundle contains all public root certificates
- path (CA_PATH) is selected based on Linux distribution -> compatible with debian, ubuntu, centos, rhel and ami
- verified on Ubuntu 18.04., CentOS 8, RHEL8, Amazon AMI 2, Debian 9
- remove checking of gen2 account 
**Steps to verify**
1. copy script to Linux distribution
2. run script `sudo bash configure-linux.sh - a <subdomain> -u <user>`

[LOG-8159] Use CA file with public root certificates

---

Modular Scripts/Apache2/configure-apache.sh

**Description:**
- https://swicloud.atlassian.net/browse/LOG-8200
- replace $DefaultNetstreamDriverCAFile path to Loggly certificate for the path to CA bundle (root certificates) stored in OS truststore
- more information: https://documentation.solarwinds.com/en/Success_Center/loggly/Content/admin/upgrade-tls-certificate.htm
- verified on supported distributions: Ubuntu, Debian, RHEL, CentOS , Amazon AMI
- upload to the public available S3 bucket will be done in JIRA ticket 
- for testing: it's necessary to use/download the newest version of configure-linux.sh script + remove the 5th line (curl ...) in configure-apache.sh

[LOG-8200] Apache script update - use truststore

---

Modular Scripts/Tomcat/configure-tomcat.sh

[JIRA task link](https://swicloud.atlassian.net/browse/LOG-8203)
Replaced cert file `$DefaultNetstreamDriverCAFile` path to the path in the truststore. 
Verified on Debian.
download the updated tomcat script and run it

[LOG-8203] Update tomcat script

---

Modular Scripts/File Monitoring/configure-file-monitoring.sh

**Description:**
- https://swicloud.atlassian.net/browse/LOG-8201
- replace `$DefaultNetstreamDriverCAFile` path to Loggly certificate for the path to CA bundle (root certificates) stored in OS truststore
-more information: https://documentation.solarwinds.com/en/Success_Center/loggly/Content/admin/upgrade-tls-certificate.htm
- verified on supported distributions: Ubuntu, Debian, RHEL, CentOS , Amazon AMI
- upload to the public available S3 bucket will be done in [JIRA ticket](https://swicloud.atlassian.net/browse/LOG-8469)
- for testing: it's necessary to use/download the newest version of [configure-linux.sh](https://github.com/loggly/install-script/blob/master/Linux%20Script/configure-linux.sh) script + remove the 5th line (_curl ..._) in configure-file-monitoring.sh

[LOG-8201] Linux file monitoring script update - use truststore

---

Modular Scripts/Nginx/configure-nginx.sh

**Description:**
- https://swicloud.atlassian.net/browse/LOG-8202
- replace $DefaultNetstreamDriverCAFile path to Loggly certificate for the path to CA bundle (root certificates) stored in OS truststore
- more information: https://documentation.solarwinds.com/en/Success_Center/loggly/Content/admin/upgrade-tls-certificate.htm
- verified on supported distributions: Ubuntu, Debian, RHEL, CentOS , Amazon AMI
- upload to the public available S3 bucket will be done in different JIRA ticket 
**Testing:**
- download this version of script and run it

[LOG-8202] Update CA path for nginx script

---

AWSscripts/SQS3script.py

**SQS3script.py updated**
A purpose of this update is that when the script does not find the S3 bucket, it might be caused by the fact the SQS queue and the S3 bucket are in different regions, which is not supported by AWS. This is displayed to the user who runs the script, when the bucket is not found. 
Next step is to update documentation.

LOG-7362 Updated message when the S3 bucket is not found.

---

Linux Script/README.md
Linux Script/configure-linux.sh

https://swicloud.atlassian.net/browse/LOG-12482
**Summary:**
When parsing token from json we were expecting the "tokens" attribute to be at the first place in the json structure. Maybe with python update the json structure changed a bit, now "tokens" attr is not at the first place which causes parsing the token to fail. I changed the parsing to take the first token and not to care about the position of the attributes.
**How to test:**
- have Linux environment (I used Loggly container which runs Linux - you will need to install additional packages by: `apt-get update & apt-get install iputils-ping & apt-get install rsyslog rsyslog-doc`, but it would be great if you could use something else so we'll have it tested in different environments)
- get the script `Linux …

LOG-12482 fix reading token

---

Linux Script/configure-linux.sh

https://swicloud.atlassian.net/browse/LOG-12569
When comparing versions of rsyslog there was a bug where arguments wouldn't match because of a space.
Surrounding this variables with quotes prevent the arguments to split.

LOG-12569 Put rsyslog version arguments into quotes

---

Linux Script/configure-linux.sh

Adjusted installation to use rsyslog-openssl for Amazon linux 2023 instead of default rsyslog-gnutls package

G1C-1773 add amazon linux 2023 support
